# mock_data.py

from models import Song

MOCK_SONGS = [
    Song(title="Last Last", artist="Burna Boy", album="Love, Damini", duration=164, filepath="/music/burna/last_last.mp3"),
    Song(title="Calm Down", artist="Rema", album="Rave & Roses Ultra", duration=220, filepath="/music/rema/calm_down.mp3"),
    Song(title="Unavailable (feat. Musa Keys)", artist="Davido", album="Timeless", duration=178, filepath="/music/davido/unavailable.mp3"),
    Song(title="Amapiano", artist="Asake & Olamide", album="Work of Art", duration=198, filepath="/music/asake/amapiano.mp3"),
    Song(title="Holy Ghost", artist="Omah Lay", album="Boy Alone", duration=171, filepath="/music/omah/holy_ghost.mp3"),
    Song(title="Buga (Lo Lo Lo)", artist="Kizz Daniel", album="Barnabas", duration=162, filepath="/music/kizz/buga.mp3"),
    Song(title="Rush", artist="Ayra Starr", album="19 & Dangerous", duration=165, filepath="/music/ayra/rush.mp3"),
    Song(title="Elon Musk", artist="Shallipopi", album="Presido La Pluto", duration=155, filepath="/music/shalli/elon_musk.mp3"),
    Song(title="Sability", artist="Ayra Starr", album="Sability (Single)", duration=170, filepath="/music/ayra/sability.mp3"),
    Song(title="Peru", artist="Fireboy DML", album="Peru (Single)", duration=162, filepath="/music/fireboy/peru.mp3"),
    Song(title="Me & U", artist="Tems", album="Born in the Wild", duration=195, filepath="/music/tems/me_and_u.mp3"),
    Song(title="Free Mind", artist="Tems", album="If Orange Was a Place", duration=225, filepath="/music/tems/free_mind.mp3"),
    Song(title="Raindance (feat. Tems)", artist="Dave", album="The Boy Who Played the Harp", duration=219, filepath="/music/dave/raindance.mp3"),
    Song(title="Damages", artist="Tems", album="For Broken Ears", duration=168, filepath="/music/tems/damages.mp3"),
    Song(title="Love Me JeJe", artist="Tems", album="Born in the Wild", duration=170, filepath="/music/tems/love_me_jeje.mp3"),
    Song(title="Monalisa", artist="Lojay & Sarz", album="Gangsters & Lovers", duration=210, filepath="/music/lojay/monalisa.mp3"),
    Song(title="Outside", artist="BNXN", album="Sorry I'm Late", duration=175, filepath="/music/bnxn/outside.mp3"),
    Song(title="Abracadabra (feat. Davido & Mr Eazi)", artist="BOJ", album="Gbagada Express", duration=190, filepath="/music/boj/abracadabra.mp3"),
    Song(title="Lock In", artist="BOJ", album="SPIRAL", duration=160, filepath="/music/boj/lock_in.mp3"),
    Song(title="Culture (feat. Enny)", artist="BOJ", album="Gbagada Express", duration=215, filepath="/music/boj/culture.mp3"),
    Song(title="Final Destination", artist="Cruel Santino", album="Subaru Boys", duration=205, filepath="/music/santino/final_destination.mp3"),
    Song(title="Shako", artist="BOJ", album="12 Summers (Summerfornication)", duration=180, filepath="/music/boj/shako.mp3"),
    Song(title="Bad Man", artist="Tiwa Savage", album="Celia", duration=185, filepath="/music/tiwa/bad_man.mp3"),
    Song(title="In a Loop (feat. BOJ & Moliy)", artist="Mellissa", album="In a Loop (Single)", duration=175, filepath="/music/mellissa/in_a_loop.mp3"),
    Song(title="MIDDLE CHILD", artist="J. Cole", album="Revenge of the Dreamers III", duration=213, filepath="/music/jcole/middle_child.mp3"),
    Song(title="a m a r i", artist="J. Cole", album="The Off-Season", duration=173, filepath="/music/jcole/amari.mp3"),
    Song(title="p r i d e . i s . t h e . d e v i l", artist="J. Cole feat. Lil Baby", album="The Off-Season", duration=243, filepath="/music/jcole/pride_is_the_devil.mp3"),
    Song(title="Wet Dreamz", artist="J. Cole", album="2014 Forest Hills Drive", duration=279, filepath="/music/jcole/wet_dreamz.mp3"),
    Song(title="Power Trip (feat. Miguel)", artist="J. Cole", album="Born Sinner", duration=250, filepath="/music/jcole/power_trip.mp3"),
    Song(title="G.O.M.D.", artist="J. Cole", album="2014 Forest Hills Drive", duration=301, filepath="/music/jcole/gomd.mp3"),
    Song(title="No Role Modelz", artist="J. Cole", album="2014 Forest Hills Drive", duration=272, filepath="/music/jcole/no_role_modelz.mp3"),
    Song(title="Starlight", artist="Dave", album="Starlight (Single)", duration=200, filepath="/music/dave/starlight.mp3"),
    Song(title="175 Months", artist="Dave", album="The Boy Who Played the Harp", duration=274, filepath="/music/dave/175_months.mp3"),
    Song(title="Location (feat. Burna Boy)", artist="Dave", album="Psychodrama", duration=240, filepath="/music/dave/location.mp3"),
    Song(title="Black", artist="Dave", album="Psychodrama", duration=267, filepath="/music/dave/black.mp3"),
    Song(title="Chapter 16", artist="Dave & Kano", album="The Boy Who Played the Harp", duration=380, filepath="/music/dave/chapter_16.mp3"),
    Song(title="Fairchild", artist="Dave & Nicole Blakk", album="The Boy Who Played the Harp", duration=346, filepath="/music/dave/fairchild.mp3"),
    Song(title="Raindance", artist="Dave & Tems", album="The Boy Who Played the Harp", duration=204, filepath="/music/dave/raindance.mp3"),
    Song(title="Funky Friday (feat. Fredo)", artist="Dave", album="Funky Friday (Single)", duration=258, filepath="/music/dave/funky_friday.mp3"),
    Song(title="Sprinter (feat. Central Cee)", artist="Dave", album="Split Decision EP", duration=228, filepath="/music/dave/sprinter.mp3"),
    Song(title="Back In Uni", artist="Blaqbonez", album="Young Preacher", duration=180, filepath="/music/blaqbonez/back_in_uni.mp3"),
    Song(title="ODG", artist="Nonso Amadi", album="When It Blows", duration=195, filepath="/music/nonso/odg.mp3"),
    Song(title="Ask About Me", artist="MohBad", album="Blessed EP", duration=180, filepath="/music/mohbad/ask_about_me.mp3"),
    Song(title="Dog Eat Dog II", artist="ODUMODUBLVCK", album="Odiegwu", duration=190, filepath="/music/odu/dog_eat_dog_ii.mp3"),
    Song(title="Story Time", artist="Falz", album="The Feast", duration=358, filepath="/music/falz/story_time.mp3"),
    Song(title="Ghetto Love", artist="Wizkid", album="Ghetto Love (Single)", duration=170, filepath="/music/wizkid/ghetto_love.mp3"),
    Song(title="Chop My Money (feat. Akon & May D)", artist="P-Square", album="The Invasion", duration=215, filepath="/music/psquare/chop_my_money.mp3"),
]